// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5zP6uX--IZ2LVkaTaScSHYH4baMwJN0M',
    appId: '1:397690114481:web:fc733417a6e8c39f182d90',
    messagingSenderId: '397690114481',
    projectId: 'kronopunch',
    authDomain: 'kronopunch.firebaseapp.com',
    storageBucket: 'kronopunch.firebasestorage.app',
    measurementId: 'G-CGS1NHNW75',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmLkrT9I3z7h9s-NvxWZFObCEEgbMX9fU',
    appId: '1:397690114481:android:97d6c8224e3dd1de182d90',
    messagingSenderId: '397690114481',
    projectId: 'kronopunch',
    storageBucket: 'kronopunch.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAySEYWORSPkRI0--xArCC7dkw04FUzkGo',
    appId: '1:397690114481:ios:df563bc02b567e2d182d90',
    messagingSenderId: '397690114481',
    projectId: 'kronopunch',
    storageBucket: 'kronopunch.firebasestorage.app',
    iosBundleId: 'com.krono.kronopunch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAySEYWORSPkRI0--xArCC7dkw04FUzkGo',
    appId: '1:397690114481:ios:df563bc02b567e2d182d90',
    messagingSenderId: '397690114481',
    projectId: 'kronopunch',
    storageBucket: 'kronopunch.firebasestorage.app',
    iosBundleId: 'com.krono.kronopunch',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5zP6uX--IZ2LVkaTaScSHYH4baMwJN0M',
    appId: '1:397690114481:web:70d374e1eec4b276182d90',
    messagingSenderId: '397690114481',
    projectId: 'kronopunch',
    authDomain: 'kronopunch.firebaseapp.com',
    storageBucket: 'kronopunch.firebasestorage.app',
    measurementId: 'G-5BXE3S8YHY',
  );
}
